version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=no
      - MONGO_INITDB_DATABASE=users
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
